    #ifndef RUST_SCALE_CODEC_WRAPPER_H
    #define RUST_SCALE_CODEC_WRAPPER_H

    /* Generated by cbindgen */

    #include <stdarg.h>
    #include <stdbool.h>
    #include <stddef.h>
    #include <stdint.h>

    typedef struct ScaleEncodedResult {
    uint8_t *ptr;
    size_t len;
    } ScaleEncodedResult;

    struct ScaleEncodedResult encode_string_to_scale(const char *input_c_str);

    char *decode_scale_to_string(const uint8_t *bytes_ptr, size_t bytes_len);

    void free_scale_encoded_result(struct ScaleEncodedResult result);

    void free_decoded_string(char *c_str_ptr);

    #endif 
